name: Selenium tests

on:
  workflow_dispatch:

env:
  ALLURE_RESULTS: "/home/runner/work/AF/AF/AF/bin/Debug/net8.0/allure-results"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect environment information
        id: env_info
        run: |
          echo "environment=${{ github.event.inputs.tags }}" >> environment.properties
          echo "url=${{ vars.URL }}" >> environment.properties
          echo "os_platform=$(uname -s)" >> environment.properties
          echo "os_version=$(uname -v)" >> environment.properties
          echo "chrome_version=$(google-chrome --version)" >> environment.properties
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Execute all unit tests in the solution
      - name: Execute Positive Selenium tests
        run: dotnet test

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Put environment information in file
        if: always()
        run: cp environment.properties ${{ env.ALLURE_RESULTS }}/environment.properties

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: ${{ env.ALLURE_RESULTS }}

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
